Reformat files
vrtbl/passerine pull request #63
Opened 2021-11-08 18:49 UTC by Chinay-Domitrix

Reformatted the Rust, Markdown (and superscripted all the †s in the readme), SVG, and YAML files according to conventions; never touched Passerine files.

2021-11-08 20:32 UTC, slightknack requested changes
Thank you so much for taking the time to format the codebase and fix some typos. I'd like to merge the changes to the Markdown, `.github/`, and `.svg`, but before I merge the mass changes to the Rust portion of the codebase, I think I should provide some context. I write this in a comment later down, but I'll move it here for ease-of-viewing:

> Compilers tend to be sets of transformations on highly-structured tree-like data, which means that Passerine uses `match` extensively. Although I appreciate the consistency tools like `rustfmt` offer for enforcing code structure, they tend not to align match arms. Using `rustfmt` with Passerine is an ongoing discussion https://github.com/vrtbl/passerine/issues/40, but until https://github.com/rust-lang/rustfmt/issues/894 is resolved I value the improved readability of aligned match expressions over programmatically enforced stylistic consistency.

Essentially, by default `rustfmt` mangles some organizational patterns I find essential for readability, and I'm waiting on an upstream issue before enforcing the use of the tool.

Other than that, looks great! There are a few minor stylistic changes in the README that need to be addressed, but other than removing/splitting out the Rust changes into a separate PR, I think it looks about ready to merge. Thanks you!

2021-11-08 20:32 UTC, slightknack commented on src/common/data.rs
> -            Data::Kind(_)     => unreachable!("Can not display naked labels"),
Compilers tend to be sets of transformations on highly-structured tree-like data, which means that Passerine uses `match` extensively. Although I appreciate the consistency tools like `rustfmt` offer for enforcing code structure, they tend not to align match arms. Using `rustfmt` with Passerine is an ongoing discussion https://github.com/vrtbl/passerine/issues/40, but until https://github.com/rust-lang/rustfmt/issues/894 is resolved I value the improved readability of aligned match expressions over programmatically enforced stylistic consistency. Hope this makes sense!

2021-11-08 20:32 UTC, slightknack commented on src/common/lambda.rs
> -            },
I know I probably sounds like a broken record at this point, but another stylistic thing: I prefer trailing commas in match statements, even when used with a block.

2021-11-08 20:32 UTC, slightknack commented on src/common/lambda.rs
> -            if i > &index { break; }
I think single-line if-expressions should be placed on a single line.

2021-11-08 20:32 UTC, slightknack commented on src/common/lambda.rs
> -                    writeln!(f, "Load Con\t{}\t{:?}", constant_index, self.constants[constant_index])?;
Breaking this across multiple lines does not improve readability. This whole expression probably needs some cleanup, though.

2021-11-08 20:32 UTC, slightknack commented on src/common/number.rs
> -    let chunk     = 0b1000_0000;
Multiple `let` statements ditto `match` arms.

2021-11-08 20:32 UTC, slightknack commented on src/common/number.rs
> -         }
Good catch!

2021-11-08 20:32 UTC, slightknack commented on src/common/source.rs
> -    pub path:     PathBuf,
Ditto `struct` fields, `match` arms, and `let` expressions. What can I say, I like it when things align nicely ;P

2021-11-08 20:32 UTC, slightknack commented on src/common/span.rs
> -              && self.end() > other.end())
I think this is more readable, but it should probably be broken up into a couple expressions.

2021-11-08 20:32 UTC, slightknack commented on src/common/span.rs
> +        }
I'm not a huge fan of breaking single expressions in blocks across multiple lines unless it really improves readability. I know readability is subjective; I think the amount of space source code occupies should be correlated with how difficult that code is to understand.

2021-11-08 20:32 UTC, slightknack commented on src/common/span.rs
> -            write!(f, "Span {{ {:?}, ({}, {}) }}", self.contents(), self.offset, self.length)
Same here: multiple lines doesn't add much. I know this was probably automatically formatted, but this is why I like to configure my automatic formatters.

2021-11-08 22:19 UTC, Chinay-Domitrix commented on README.md
> +> **⚠️ Note that Passerine is a _work in progress_: features mentioned in this overview may not be implemented yet.**
That was Prettier, not me lol

2021-11-08 22:28 UTC, Chinay-Domitrix commented on ARCHITECTURE.md
> +
Fair; the newline after headings is something enforced both by the Markdown error checker I use and by Prettier.

2021-11-08 22:56 UTC, Chinay-Domitrix commented
As stated in [one of the reviews on the PR](https://github.com/vrtbl/passerine/pull/63#discussion_r745063869), most of the actual reformatting was done automatically (with either the official Rust extension for Open VSX or Prettier), and to be quite frank, I have little to no experience with Rust because of my background in Java and Kotlin, hence why all the manual changes are on the Markdown files and not the Rust files; I don't trust that I would be capable of making any Rust changes without fundamentally breaking something. In general, I'll likely undo my commit and then undo the Rust file changes before recommitting and pushing.

2021-11-09 05:54 UTC, slightknack commented
No worries, and thank you for going through and correcting the markdown files by hand.

> In general, I'll likely undo my commit and then undo the Rust file changes before recommitting and pushing. I'll probably get around to it tomorrow.

Sounds like a plan :)

2021-11-10 18:42 UTC, Chinay-Domitrix commented
I did it

2021-11-10 18:49 UTC, slightknack commented
Let me take a look, 1 sec.

2021-11-10 18:54 UTC, slightknack requested changes
@Chinay-Domitrix I think there are still some changes to the Rust portion of the project, as well as some markdown changes (i.e. newlines after headings, italics, etc.) that need to be reverted. Can you double checked you've resolved and pushed everything? The number of files changed in this PR should be 4 or 5.

I think some changes may've been reverted when you merged `5a5d5e3` to produce `e22283e`?

2021-11-10 19:09 UTC, Chinay-Domitrix commented
> @Chinay-Domitrix I think there are still some changes to the Rust portion of the project, as well as some markdown changes (i.e. newlines after headings, italics, etc.) that need to be reverted. Can you double checked you've resolved and pushed everything? The number of files changed in this PR should be 4 or 5.
> 
> I think some changes may've been reverted when you merged `5a5d5e3` to produce `e22283e`?

maybe I'll check

2021-11-10 19:20 UTC, Chinay-Domitrix commented
Hmm im gonna jank this gimme a sec cause otherwise I have to manually undo everything

2021-11-10 19:22 UTC, slightknack commented
> Hmm im gonna jank this gimme a sec cause otherwise I have to manually undo everything

Kk. If it's easier, you could probably just open another PR and close this one.

2021-11-10 21:38 UTC, closed without merging