Reformat and minor Markdown touch-ups (attempt 2)
vrtbl/passerine pull request #64
Opened 2021-11-10 23:57 UTC by Chinay-Domitrix

2021-11-11 04:57 UTC, slightknack requested changes
Thanks for incorporating the feedback on the last PR! There are just a couple of things, and then it'll be ready for merging.

2021-11-11 04:57 UTC, slightknack commented on README.md
> +of _different types_ of expressions.
Two quick things, then I'll merge this PR:

1. I think your formatter added 80-column line breaks to the markdown file. Please remove them
2. The italics `*hello*` are still being changed to `_hello_`.

2021-11-11 04:57 UTC, slightknack commented on README.md
> -
These newlines are here on purpose, same for all other listings.

2021-11-11 04:57 UTC, slightknack commented on README.md
> +> In the following table, `p` is a nested sub-pattern. | pattern | example | destructures | | -------- | ----------------- | --------------------------------------------------------------------------
I think this table got botched...

2021-11-11 20:08 UTC, Chinay-Domitrix commented
I'll take a look and fix everything in a bit

2021-11-23 05:52 UTC, slightknack commented
Any updates?

2022-03-18 22:02 UTC, slightknack commented
With the introduction of the (WIP) [Codex](https://codex.passerine.io), a lot of information in the README will be moving there. Because of this, the README will look a lot different than it does today (especially once #52 is merged). Because of this, I'm closing this PR. If you'd like to help write the Codex, feel free to open a PR [on its repo](https://github.com/vrtbl/codex).

2022-03-18 22:02 UTC, closed without merging